### ISSUE TITLE
User Management - web dashboard

### ISSUE THREAD

**Issue by StijnHD** [veritrans/veritrans.github.io#139] opened 2019-12-25 03:28 UTC
Why does an "OPERATIONS STAFF" user account have access to change the environment between "PRODUCTION" or "SANDBOX"

Is this not a Tech Setting that should only be available for "ADMINISTRATOR" users ?

**Comment by rizdaprasetya** [comment] 2019-12-26 10:02
Hi @StijnHD for now that is expected, Operation Staff are allowed to see & manage transaction on Production & Sandbox, with same capability. But they are only switching between production-sandbox within their account only, it does not mean it will Switch the entire Midtrans account.
If you wish for the account to login directly to Production, they can login via this url https://dashboard.midtrans.com

can you describe/explain what is your concern?

**Comment by rizdaprasetya** [comment] 2020-01-13 05:49
[Closing abandoned issue]
Please comment/reply if you consider the issue is not solved yet.

**Closed by rizdaprasetya** 2020-01-13 05:49 UTC
